/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconHeroiconsOutlineCheck: typeof import('~icons/heroicons-outline/check')['default']
    IconHeroiconsOutlineCheckCircle: typeof import('~icons/heroicons-outline/check-circle')['default']
    IconHeroiconsOutlineClipboardDocument: typeof import('~icons/heroicons-outline/clipboard-document')['default']
    IconHeroiconsOutlineKey: typeof import('~icons/heroicons-outline/key')['default']
    IconHeroiconsOutlinePaperAirplane: typeof import('~icons/heroicons-outline/paper-airplane')['default']
    IconHeroiconsOutlinePencilSquare: typeof import('~icons/heroicons-outline/pencil-square')['default']
    IconHeroiconsOutlineTrash: typeof import('~icons/heroicons-outline/trash')['default']
  }
}
