/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconHeroiconsOutlineCheck: typeof import('~icons/heroicons-outline/check')['default']
    IconHeroiconsOutlinePaperAirplane: typeof import('~icons/heroicons-outline/paper-airplane')['default']
  }
}
